
version: 2

sources:
  - name: coffee_shop
    project: analytics-engineers-club 
    tables: 
      - name: customers
        columns:
          - name: id
            tests:
              - unique
              - not_null
      - name: orders
        columns:
          - name: id
            tests:
              - unique
              - not_null 
        freshness:
          warn_after:
            count: 12
            period: hour
        loaded_at_field: created_at
  - name: web_tracking
    project: analytics-engineers-club 
    tables: 
      - name: pageviews
        columns: 
          - name: id
            tests:
              - unique
              - not_null
models:
  - name: customers
    description: Cleaned up data about our customers.
    columns:
      - name: id
        description: Primary key of the model
        tests:
          - unique
          - not_null       
  - name: monthly_customers
    description: Number of new customers by month.
    columns:
      - name: signup_month
        description: Month of the year.
        tests: 
          - unique
          - not_null
      - name: new_customers
        description: Number of new cutomers per month.
  - name: pageviews_user_stiching
    description: Table containing pageview data where all of the visitors with known customer_id are assigned the same visitor_id.  Users' browsing sessions are linked together when there is evidence they are in fact the same user.
    columns: 
      - name: id
        description: Primary key of the model.
        tests:
          - unique
          - not_null  
      - name: stiched_visitor_id
        description: The unique id of a visitor.
        tests:
          - bespoke_pageviews_user_stiching
          - not_null
      - name: device_type
        description: Type of a device used during a visit.
      - name: timestamp
        description: Date and time when the visit started.
      - name: page
        description: Page visited on our website.
      - name: customer_id
        description: The unique id of a customer (null if not a customer).    